# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_ver_meses.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1930, 1055)
        self.home_widget = QtWidgets.QWidget(MainWindow)
        self.home_widget.setObjectName("home_widget")
        self.radioButton_entrada_2 = QtWidgets.QRadioButton(self.home_widget)
        self.radioButton_entrada_2.setGeometry(QtCore.QRect(330, 320, 101, 31))
        self.radioButton_entrada_2.setStyleSheet("background-color: transparent;\n"
"font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"")
        self.radioButton_entrada_2.setObjectName("radioButton_entrada_2")
        self.radioButton_entrada_3 = QtWidgets.QRadioButton(self.home_widget)
        self.radioButton_entrada_3.setGeometry(QtCore.QRect(700, 320, 101, 31))
        self.radioButton_entrada_3.setStyleSheet("background-color: transparent;\n"
"font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"")
        self.radioButton_entrada_3.setObjectName("radioButton_entrada_3")
        self.radioButton_entrada_4 = QtWidgets.QRadioButton(self.home_widget)
        self.radioButton_entrada_4.setGeometry(QtCore.QRect(890, 320, 101, 31))
        self.radioButton_entrada_4.setStyleSheet("background-color: transparent;\n"
"font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"")
        self.radioButton_entrada_4.setObjectName("radioButton_entrada_4")
        self.radioButton_entrada_5 = QtWidgets.QRadioButton(self.home_widget)
        self.radioButton_entrada_5.setGeometry(QtCore.QRect(1090, 320, 101, 31))
        self.radioButton_entrada_5.setStyleSheet("background-color: transparent;\n"
"font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"")
        self.radioButton_entrada_5.setObjectName("radioButton_entrada_5")
        self.radioButton_entrada_6 = QtWidgets.QRadioButton(self.home_widget)
        self.radioButton_entrada_6.setGeometry(QtCore.QRect(1290, 320, 101, 31))
        self.radioButton_entrada_6.setStyleSheet("background-color: transparent;\n"
"font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"")
        self.radioButton_entrada_6.setObjectName("radioButton_entrada_6")
        self.radioButton_entrada_7 = QtWidgets.QRadioButton(self.home_widget)
        self.radioButton_entrada_7.setGeometry(QtCore.QRect(1480, 320, 101, 31))
        self.radioButton_entrada_7.setStyleSheet("background-color: transparent;\n"
"font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"")
        self.radioButton_entrada_7.setObjectName("radioButton_entrada_7")
        self.radioButton_entrada_8 = QtWidgets.QRadioButton(self.home_widget)
        self.radioButton_entrada_8.setGeometry(QtCore.QRect(520, 320, 101, 31))
        self.radioButton_entrada_8.setStyleSheet("background-color: transparent;\n"
"font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"")
        self.radioButton_entrada_8.setObjectName("radioButton_entrada_8")
        self.pushButton = QtWidgets.QPushButton(self.home_widget)
        self.pushButton.setGeometry(QtCore.QRect(330, 420, 481, 51))
        self.pushButton.setStyleSheet("font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.home_widget)
        self.pushButton_2.setGeometry(QtCore.QRect(1090, 420, 481, 51))
        self.pushButton_2.setStyleSheet("font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.home_widget)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 500, 481, 51))
        self.pushButton_3.setStyleSheet("font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.home_widget)
        self.pushButton_4.setGeometry(QtCore.QRect(1090, 500, 481, 51))
        self.pushButton_4.setStyleSheet("font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.home_widget)
        self.pushButton_5.setGeometry(QtCore.QRect(330, 580, 481, 51))
        self.pushButton_5.setStyleSheet("font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.home_widget)
        self.pushButton_6.setGeometry(QtCore.QRect(1090, 580, 481, 51))
        self.pushButton_6.setStyleSheet("font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.home_widget)
        self.pushButton_7.setGeometry(QtCore.QRect(330, 660, 481, 51))
        self.pushButton_7.setStyleSheet("font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.home_widget)
        self.pushButton_8.setGeometry(QtCore.QRect(1090, 660, 481, 51))
        self.pushButton_8.setStyleSheet("font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.home_widget)
        self.pushButton_9.setGeometry(QtCore.QRect(330, 740, 481, 51))
        self.pushButton_9.setStyleSheet("font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.home_widget)
        self.pushButton_10.setGeometry(QtCore.QRect(1090, 740, 481, 51))
        self.pushButton_10.setStyleSheet("font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.home_widget)
        self.pushButton_11.setGeometry(QtCore.QRect(330, 820, 481, 51))
        self.pushButton_11.setStyleSheet("font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.home_widget)
        self.pushButton_12.setGeometry(QtCore.QRect(1090, 820, 481, 51))
        self.pushButton_12.setStyleSheet("font: 22pt \"Sans Serif Collection\";\n"
"color: rgb(51, 51, 51);\n"
"\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.label = QtWidgets.QLabel(self.home_widget)
        self.label.setGeometry(QtCore.QRect(330, 370, 1241, 16))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(2,0,36,1), stop:1 rgba(9,121,35,1), stop:2 rgba(0,212,255,1));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_13 = QtWidgets.QPushButton(self.home_widget)
        self.pushButton_13.setGeometry(QtCore.QRect(340, 902, 1231, 91))
        self.pushButton_13.setStyleSheet("font: 22pt \"Sans Serif Collection\";\n"
"\n"
"background-color: rgb(0, 210, 135);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"border-radius:10px;\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        MainWindow.setCentralWidget(self.home_widget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionProcurar = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images_home/buscar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionProcurar.setIcon(icon)
        self.actionProcurar.setObjectName("actionProcurar")
        self.actionCadastrar = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images_home/create.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastrar.setIcon(icon1)
        self.actionCadastrar.setObjectName("actionCadastrar")
        self.actionApagar = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images_home/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionApagar.setIcon(icon2)
        self.actionApagar.setObjectName("actionApagar")
        self.actionAtualizar = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images_home/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAtualizar.setIcon(icon3)
        self.actionAtualizar.setObjectName("actionAtualizar")
        self.actionVer_Meses = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images_home/olhinho.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVer_Meses.setIcon(icon4)
        self.actionVer_Meses.setObjectName("actionVer_Meses")
        self.actionNovo_mes = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images_home/novo_mes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNovo_mes.setIcon(icon5)
        self.actionNovo_mes.setObjectName("actionNovo_mes")
        self.actionFechar_mes = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images_home/fechar_mes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFechar_mes.setIcon(icon6)
        self.actionFechar_mes.setObjectName("actionFechar_mes")
        self.actionDetalhes_do_Saldo = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images_home/saldo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDetalhes_do_Saldo.setIcon(icon7)
        self.actionDetalhes_do_Saldo.setObjectName("actionDetalhes_do_Saldo")
        self.actionFechamento_do_Dia = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images_home/fechamento_dia.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFechamento_do_Dia.setIcon(icon8)
        self.actionFechamento_do_Dia.setObjectName("actionFechamento_do_Dia")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_entrada_2.setText(_translate("MainWindow", "2024"))
        self.radioButton_entrada_3.setText(_translate("MainWindow", "2026"))
        self.radioButton_entrada_4.setText(_translate("MainWindow", "2027"))
        self.radioButton_entrada_5.setText(_translate("MainWindow", "2028"))
        self.radioButton_entrada_6.setText(_translate("MainWindow", "2029"))
        self.radioButton_entrada_7.setText(_translate("MainWindow", "2030"))
        self.radioButton_entrada_8.setText(_translate("MainWindow", "2025"))
        self.pushButton.setText(_translate("MainWindow", "JANEIRO"))
        self.pushButton_2.setText(_translate("MainWindow", "FEVEREIRO"))
        self.pushButton_3.setText(_translate("MainWindow", "MARÇO"))
        self.pushButton_4.setText(_translate("MainWindow", "ABRIL"))
        self.pushButton_5.setText(_translate("MainWindow", "MAIO"))
        self.pushButton_6.setText(_translate("MainWindow", "JUNHO"))
        self.pushButton_7.setText(_translate("MainWindow", "JULHO"))
        self.pushButton_8.setText(_translate("MainWindow", "AGOSTO"))
        self.pushButton_9.setText(_translate("MainWindow", "SETEMBRO"))
        self.pushButton_10.setText(_translate("MainWindow", "OUTUBRO"))
        self.pushButton_11.setText(_translate("MainWindow", "NOVEMBRO"))
        self.pushButton_12.setText(_translate("MainWindow", "DEZEMBRO"))
        self.pushButton_13.setText(_translate("MainWindow", "VER RESUMO ANUAL"))
        self.actionProcurar.setText(_translate("MainWindow", "Procurar"))
        self.actionCadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.actionApagar.setText(_translate("MainWindow", "Apagar"))
        self.actionAtualizar.setText(_translate("MainWindow", "Atualizar"))
        self.actionVer_Meses.setText(_translate("MainWindow", "Ver Meses"))
        self.actionNovo_mes.setText(_translate("MainWindow", "Novo Mês"))
        self.actionFechar_mes.setText(_translate("MainWindow", "Fechar Mês"))
        self.actionDetalhes_do_Saldo.setText(_translate("MainWindow", "Detalhes do Saldo"))
        self.actionFechamento_do_Dia.setText(_translate("MainWindow", "Fechamento do Dia"))
        
import images_home.resources


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
